package:
  name: cvannotate
  version: 0.1.0

source:
  path: ../

build:
  number: 0
  noarch: python
  entry_points:
    - cvannotate = cvannotate.cli:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=67.0
  run:
    - python >=3.8
    - typer
    - pillow
    - defusedxml

test:
  imports:
    - cvannotate
    - cvannotate.cli
    - cvannotate.convert
    - cvannotate.converters
    - cvannotate.types
  commands:
    - cvannotate --help
    - cvannotate convert --help

about:
  home: https://github.com/Echo9k/cv-format-annotation-converters
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Convert object detection annotations across formats
  description: |
    CVAnnotate is a Python package that provides utilities to convert
    object detection annotations between different formats including:
    YOLO, Pascal VOC, and MS COCO. It includes both a command-line interface
    and a Python API for programmatic use.
  doc_url: https://github.com/Echo9k/cv-format-annotation-converters
  dev_url: https://github.com/Echo9k/cv-format-annotation-converters

extra:
  recipe-maintainers:
    - Echo9k
