package:
  name: cvannotate
  version: "0.1.0"

source:
  url: https://pypi.io/packages/source/c/cvannotate/cvannotate-0.1.0.tar.gz
  sha256: ""

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - typer >=0.9
    - pillow
    - lxml

about:
  home: https://github.com/example/cvannotate
  summary: "Annotation format converters"
  license: MIT
