{% set name = "cvannotate" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# NOTE: For conda-forge submission, this should point to PyPI (pypi.org)
# Currently using test-pypi for development/testing
source:
  url: https://test-files.pythonhosted.org/packages/09/3a/e66bd39c8703881cffd1070cbfd20a9d56c76bdb9c5112ffee793124edcb/cvannotate-1.0.0.tar.gz
  sha256: 7a59356838d987ac3da9f8b965bff9d80e0c1914390df4233b75c8125126fb8c

build:
  number: 0
  noarch: python
  entry_points:
    - cvannotate = cvannotate.cli:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=67.0
  run:
    - python >=3.8
    - typer >=0.9.0
    - pillow >=8.0.0
    - defusedxml >=0.7.0

test:
  imports:
    - cvannotate
    - cvannotate.cli
    - cvannotate.convert
    - cvannotate.converters
    - cvannotate.types
  commands:
    - cvannotate --help
    - cvannotate convert --help

about:
  home: https://github.com/Echo9k/cv-format-annotation-converters
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Convert object detection annotations across formats (YOLO, VOC, COCO)
  description: |
    CVAnnotate is a Python package that provides utilities to convert
    object detection annotations between different formats including:
    YOLO, Pascal VOC, and MS COCO. It includes both a command-line interface
    and a Python API for programmatic use.
  doc_url: https://github.com/Echo9k/cv-format-annotation-converters#readme
  dev_url: https://github.com/Echo9k/cv-format-annotation-converters

extra:
  recipe-maintainers:
    - guillermo-alcantara  # Replace with actual conda-forge username
  dev_url: https://github.com/Echo9k/cv-format-annotation-converters

extra:
  recipe-maintainers:
    - Echo9k
