name: Update Conda Recipe

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to update to'
        required: true
        type: string
      use_test_pypi:
        description: 'Use test-PyPI instead of main PyPI'
        required: false
        type: boolean
        default: false

jobs:
  update-conda-recipe:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        
    - name: Update conda recipe (from release)
      if: github.event_name == 'release'
      run: |
        python scripts/update_conda_recipe.py cvannotate \
          --version ${{ github.event.release.tag_name }} \
          --recipe-path conda-recipe/meta.yaml
          
    - name: Update conda recipe (manual)
      if: github.event_name == 'workflow_dispatch'
      run: |
        python scripts/update_conda_recipe.py cvannotate \
          --version ${{ github.event.inputs.version }} \
          ${{ github.event.inputs.use_test_pypi && '--test-pypi' || '' }} \
          --recipe-path conda-recipe/meta.yaml
          
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: Update conda recipe for version ${{ github.event.release.tag_name || github.event.inputs.version }}'
        title: 'Update conda recipe for version ${{ github.event.release.tag_name || github.event.inputs.version }}'
        body: |
          Automatically generated PR to update conda recipe with new package information.
          
          **Changes:**
          - Updated package version
          - Updated source URL and SHA256 hash
          
          **Version:** ${{ github.event.release.tag_name || github.event.inputs.version }}
          **PyPI source:** ${{ github.event.inputs.use_test_pypi && 'test-pypi' || 'pypi' }}
        branch: update-conda-recipe-${{ github.event.release.tag_name || github.event.inputs.version }}
        delete-branch: true
